version: '3.7'

services:
  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks: 
      - shared-net 
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      restart: always
      POSTGRES_DB: kitaplik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_ROOT_PASSWORD: root
    networks: 
      - shared-net 
    volumes:
      - ./postgres/data:/backup

  app:
    image: kitaplik
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgresdb
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresdb:5432/kitaplik
      - SERVER_PORT=8082
      - spring.redis.host=redis
      - spring.redis.port=6379
    restart: always
    networks: 
      - shared-net


  
networks:
  shared-net:
    driver: bridge


  


      